name: CI Test Log

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Simulate CVE log output
        run: |
          echo "⚠️ Potential vulnerability detected: CVE-2020-36632"
          echo "Another one: CVE-2025-29512"
      - name: Log output
        run: |
          echo "Hello from AuditForge!"
          echo "This is a test for log scanning."
          echo "Unauthorized access attempt detected"
